# Unweight and augment samples

Johann Brehmer, Kyle Cranmer, Marco Farina, Felix Kling, Duccio Pappadopulo, Josh Ruderman 2018

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import matplotlib
from matplotlib import pyplot as plt
% matplotlib inline
import logging
import os

from madminer.sampling import SampleAugmenter
from madminer.sampling import multiple_benchmark_thetas
from madminer.sampling import constant_morphing_theta, multiple_morphing_thetas, random_morphing_thetas

logging.basicConfig(format='%(asctime)s  %(message)s', datefmt='%H:%M')


In [2]:
base_dir = '/Users/johannbrehmer/work/projects/madminer/diboson_mining/'
mg_dir = '/Users/johannbrehmer/work/projects/madminer/MG5_aMC_v2_6_2/'

In [3]:
sample_dir = base_dir + 'data/samples/wgamma/'
card_dir = base_dir + 'cards/wgamma/'
ufo_model_dir = card_dir + 'SMWgamma_UFO'
run_card_dir = card_dir + 'run_cards/'
mg_process_dir = base_dir + 'data/mg_processes/wgamma/'
log_dir = base_dir + 'logs/wgamma/'
temp_dir = base_dir + 'data/temp'
delphes_dir = mg_dir + 'Delphes'

## Load data (with tight cuts)

In [4]:
sa = SampleAugmenter(sample_dir + 'samples_tight.h5', debug=False)

07:50  
07:50  ------------------------------------------------------------
07:50  |                                                          |
07:50  |  MadMiner v2018.11.13                                    |
07:50  |                                                          |
07:50  |           Johann Brehmer, Kyle Cranmer, and Felix Kling  |
07:50  |                                                          |
07:50  ------------------------------------------------------------
07:50  
07:50  Loading data from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/samples/wgamma/samples_tight.h5
07:50  Found 2 parameters:
07:50     cWWW (LHA: dim6 1, maximal power in squared ME: (2,), range: (-0.02, 0.02))
07:50     cWWWtilde (LHA: dim6 2, maximal power in squared ME: (2,), range: (-0.02, 0.02))
07:50  Found 6 benchmarks:
07:50     sm: cWWW = 0.00e+00, cWWWtilde = 0.00e+00
07:50     morphing_basis_vector_1: cWWW = -6.07e-03, cWWWtilde = -1.84e-02
07:50     morphing_basis_vect

### SALLY training data

In [ ]:
for i in range(10):
    _, _, _ = sa.extract_samples_train_local(
        theta=constant_morphing_theta([0.,0.]),
        n_samples=1000000,
        folder=sample_dir + 'train_local_tight',
        filename='train_' + str(i)
    )

### RASCAL training data

In [6]:
for i in range(1):
    _ = sa.extract_samples_train_ratio(
        theta0=random_morphing_thetas(1000, [('gaussian', 0., 0.005), ('gaussian', 0., 0.005)]),
        theta1=constant_morphing_theta([0.,0.]),
        n_samples=100000,
        folder=sample_dir + 'train_ratio_tight',
        filename='train_' + str(i)
    )

07:53  Extracting training sample for ratio-based methods. Numerator hypothesis: ('random', (1000, [('gaussian', 0.0, 0.005), ('gaussian', 0.0, 0.005)])), denominator hypothesis: ('theta', array([0., 0.]))
07:55  Effective number of samples: mean 486.6725486580612, with individual thetas ranging from 38.896311231459975 to 2283.567315636974
07:56  Effective number of samples: mean 2289.484972855909, with individual thetas ranging from 2289.484972855909 to 2289.484972855909


### SCANDAL training data

In [12]:
for i in range(1):
    sa.extract_samples_train_global(
        theta=random_morphing_thetas(10000, [('gaussian', 0., 0.005), ('gaussian', 0., 0.005)]),
        n_samples=100000,
        folder=sample_dir + 'train_scandal_tight',
        filename='train_' + str(i)
    )

08:11  Extracting training sample for non-local score-based methods. Sampling and score evaluation according to ('random', (10000, [('gaussian', 0.0, 0.005), ('gaussian', 0.0, 0.005)]))
08:25  Effective number of samples: mean 478.51932520607346, with individual thetas ranging from 36.66375285490305 to 2288.62541497217


### Validation and test data

In [ ]:
_, _ = sa.extract_samples_train_plain(
    theta=constant_morphing_theta([0.,0.]),
    n_samples=1000000,
    folder=sample_dir + 'validation_tight',
    filename='validation'
)

In [ ]:
x_sm, _ = sa.extract_samples_test(
    theta=constant_morphing_theta([0.,0.]),
    n_samples=1000000,
    folder=sample_dir + 'test_tight',
    filename='test'
)

In [7]:
sa.extract_samples_test(
    theta=constant_morphing_theta([0.,0.]),
    n_samples=100000,
    folder=sample_dir + 'test_sm_tight',
    filename='test'
)

09:34  Extracting evaluation sample. Sampling according to ('theta', array([0., 0.]))
09:34  Effective number of samples: 2259.525446107569


(array([[ 1.17253738e+02,  2.30557370e+00,  8.86337244e+02, ...,
          1.52458694e+02,  3.22859440e+01, -3.47320220e-01],
        [ 2.07721146e+02, -1.81286871e+00,  6.53493440e+02, ...,
          2.81297518e+02,  6.74082272e+00,  2.98951358e+00],
        [ 1.22945518e+02,  2.69437535e-03,  1.75161849e+02, ...,
          2.54042924e+01,  7.66752857e+01, -1.36310169e+00],
        ...,
        [ 2.17523285e+02, -2.92998409e+00,  4.39063499e+02, ...,
          1.88195239e+02,  1.16738988e+01,  3.04249414e+00],
        [ 1.12007751e+02,  2.50395703e+00,  2.25418053e+02, ...,
          1.05265545e+02,  5.12473658e+00, -6.17783841e-02],
        [ 4.04335083e+02, -1.15071929e+00,  7.07115430e+02, ...,
          2.60991267e+02,  4.28514999e+01, -4.31850324e-01]]), array([[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]))

In [6]:
sa.extract_samples_test(
    theta=constant_morphing_theta([0.02,0.]),
    n_samples=100000,
    folder=sample_dir + 'test_www_tight',
    filename='test'
)

09:59  Extracting evaluation sample. Sampling according to ('theta', array([0.02, 0.  ]))
09:59  Effective number of samples: 120.6630101056156


(array([[ 2.09159668e+02,  8.27919394e-02,  9.22145328e+02, ...,
          3.31864907e+01,  2.66064620e+01, -2.82906483e+00],
        [ 4.83811859e+02, -1.65001988e+00,  1.02652408e+03, ...,
          4.56574134e+02,  1.25176430e+01, -2.51325130e-01],
        [ 4.59729767e+02, -1.43100786e+00,  2.18332224e+02, ...,
          1.06060541e+02,  3.20591797e+01,  2.69200809e+00],
        ...,
        [ 6.77438293e+02, -1.23415582e-01,  1.10320346e+03, ...,
          1.87576904e+01,  2.82283475e+01,  4.44017913e-01],
        [ 2.43731308e+02, -1.18725456e-01,  7.89251520e+02, ...,
          1.74396358e+02,  4.50046341e+01, -4.72359308e-01],
        [ 1.50232285e+02,  3.08450913e+00,  2.02594379e+03, ...,
          1.50916563e+02,  1.25974775e+01, -2.04640929e-01]]),
 array([[0.02, 0.  ],
        [0.02, 0.  ],
        [0.02, 0.  ],
        ...,
        [0.02, 0.  ],
        [0.02, 0.  ],
        [0.02, 0.  ]]))

In [12]:
sa.extract_samples_test(
    theta=constant_morphing_theta([0.005,0.]),
    n_samples=100000,
    folder=sample_dir + 'test_www_small_tight',
    filename='test'
)

10:31  Extracting evaluation sample. Sampling according to ('theta', array([0.005, 0.   ]))
10:31  Effective number of samples: 986.9461974974071


(array([[ 1.22683754e+02,  1.14082825e+00,  3.34105859e+02, ...,
          1.35082948e+02,  2.11441009e+00, -1.85818514e-02],
        [ 9.19899368e+01,  1.06257617e+00,  4.14038487e+02, ...,
          1.09658210e+02,  9.59090649e+00,  2.95605195e+00],
        [ 8.31525650e+01, -1.93947387e+00,  1.88542282e+02, ...,
          9.20281837e+01,  1.69210312e+01,  2.72308010e-01],
        ...,
        [ 9.94973145e+01, -8.27758610e-01,  1.53625769e+03, ...,
          5.25824096e+01,  1.23876439e+01, -9.19388928e-02],
        [ 1.24059525e+02, -7.23481655e-01,  1.77488305e+02, ...,
          7.05015473e+01,  3.98950083e+01,  2.58415419e+00],
        [ 9.71189270e+01, -2.72597218e+00,  1.64953684e+02, ...,
          3.84217464e+00,  3.63747485e+01, -2.68695069e+00]]),
 array([[0.005, 0.   ],
        [0.005, 0.   ],
        [0.005, 0.   ],
        ...,
        [0.005, 0.   ],
        [0.005, 0.   ],
        [0.005, 0.   ]]))

In [14]:
sa.extract_samples_test(
    theta=constant_morphing_theta([-0.005,0.]),
    n_samples=100000,
    folder=sample_dir + 'test_www_smallnegative_tight',
    filename='test'
)

10:38  Extracting evaluation sample. Sampling according to ('theta', array([-0.005,  0.   ]))
10:38  Effective number of samples: 989.1505252107842


(array([[ 1.23298172e+02,  2.58348513e+00,  2.04053212e+02, ...,
          9.44341574e+01,  1.12610386e+01,  4.90115225e-02],
        [ 8.79270554e+01,  2.30236316e+00,  9.13900053e+02, ...,
          1.36758643e+00,  6.49419596e+01,  1.53461231e+00],
        [ 1.34921570e+02,  4.59023088e-01,  2.11196001e+02, ...,
          7.72217691e+01,  7.13919538e+01,  2.07502526e+00],
        ...,
        [ 9.45649948e+01,  2.08066726e+00,  2.05641363e+02, ...,
          4.57456851e+01,  2.56162039e+01,  2.71131416e+00],
        [ 1.67094864e+02,  1.62404323e+00,  3.45389553e+02, ...,
          1.43207620e+02,  2.82108137e+01, -3.37517767e-01],
        [ 2.34366486e+02, -7.45173275e-01,  9.98064050e+02, ...,
          1.63433531e+02,  3.60964327e+00,  2.38521008e-02]]),
 array([[-0.005,  0.   ],
        [-0.005,  0.   ],
        [-0.005,  0.   ],
        ...,
        [-0.005,  0.   ],
        [-0.005,  0.   ],
        [-0.005,  0.   ]]))

In [7]:
sa.extract_samples_test(
    theta=constant_morphing_theta([0.,0.02]),
    n_samples=100000,
    folder=sample_dir + 'test_wwwtilde_tight',
    filename='test'
)

09:59  Extracting evaluation sample. Sampling according to ('theta', array([0.  , 0.02]))
09:59  Effective number of samples: 121.0377803284034


(array([[ 1.37806488e+02,  1.35081220e+00,  3.12915131e+02, ...,
          1.30661486e+02,  1.89120114e+01, -2.24675448e-01],
        [ 1.79046814e+02,  1.65292239e+00,  3.45149229e+02, ...,
          1.62311555e+02,  1.89325979e+01,  2.88270186e+00],
        [ 1.09205765e+02,  2.07176781e+00,  4.63694880e+02, ...,
          6.92713904e+01,  1.60210299e+00, -1.85390817e-02],
        ...,
        [ 3.24035828e+02, -2.45303774e+00,  4.85000356e+02, ...,
          2.32594055e+02,  1.81344728e+01,  2.89999621e+00],
        [ 1.10621330e+02, -2.04121423e+00,  4.82436452e+03, ...,
          6.99785850e+01,  4.12134563e+01,  4.93750332e-01],
        [ 1.30596710e+02,  4.55058545e-01,  4.61122608e+02, ...,
          9.18030577e+01,  5.71031895e+01, -7.59526792e-01]]),
 array([[0.  , 0.02],
        [0.  , 0.02],
        [0.  , 0.02],
        ...,
        [0.  , 0.02],
        [0.  , 0.02],
        [0.  , 0.02]]))

In [11]:
sa.extract_samples_test(
    theta=constant_morphing_theta([0.,0.005]),
    n_samples=100000,
    folder=sample_dir + 'test_wwwtilde_small_tight',
    filename='test'
)

10:31  Extracting evaluation sample. Sampling according to ('theta', array([0.   , 0.005]))
10:31  Effective number of samples: 988.5259861919268


(array([[ 9.35546631e+02, -2.98013747e-01,  1.69015191e+03, ...,
          8.08507741e+02,  2.74514074e+00,  6.96583958e-02],
        [ 3.19759857e+02, -1.58291769e+00,  8.42416084e+02, ...,
          3.74892321e+02,  6.97266550e+00,  3.12757228e+00],
        [ 1.76742737e+02, -2.83967900e+00,  3.60888451e+02, ...,
          1.19213867e+02,  3.13900352e+00,  6.06286622e-02],
        ...,
        [ 1.06591537e+02, -1.71821427e+00,  2.78371766e+02, ...,
          4.22812224e+01,  3.05732964e+01, -4.50498209e-01],
        [ 9.05896225e+01,  2.27054644e+00,  5.55068144e+02, ...,
          1.03960294e+02,  1.30264067e+01, -2.91799925e+00],
        [ 1.20789719e+02,  5.31019829e-02,  2.40338555e+03, ...,
          9.84474162e+01,  3.38142418e+01,  2.74735384e+00]]),
 array([[0.   , 0.005],
        [0.   , 0.005],
        [0.   , 0.005],
        ...,
        [0.   , 0.005],
        [0.   , 0.005],
        [0.   , 0.005]]))

In [13]:
sa.extract_samples_test(
    theta=constant_morphing_theta([0.,-0.005]),
    n_samples=100000,
    folder=sample_dir + 'test_wwwtilde_smallnegative_tight',
    filename='test'
)

10:37  Extracting evaluation sample. Sampling according to ('theta', array([ 0.   , -0.005]))
10:37  Effective number of samples: 987.564710969861


(array([[ 1.32951599e+02, -2.98489904e+00,  3.70151570e+02, ...,
          1.12577105e+02,  6.07643343e+00, -7.35909144e-02],
        [ 1.07900330e+02, -2.71692061e+00,  2.32934420e+02, ...,
          7.48271537e+01,  8.92589877e+00, -1.20320844e-01],
        [ 1.30245819e+02,  1.72092533e+00,  7.36644100e+02, ...,
          4.37636023e+01,  4.95122451e+01,  2.59473737e+00],
        ...,
        [ 1.65513168e+02, -9.71721947e-01,  7.96032643e+02, ...,
          1.30639832e+02,  4.01425286e+01,  4.59745724e-01],
        [ 9.47796783e+01, -3.07862496e+00,  2.06380654e+02, ...,
          1.01431551e+02,  1.39677137e+01,  2.94336041e+00],
        [ 1.23226509e+02, -2.50864840e+00,  2.81923381e+02, ...,
          1.15361937e+02,  1.19702688e+01,  1.66102595e-01]]),
 array([[ 0.   , -0.005],
        [ 0.   , -0.005],
        [ 0.   , -0.005],
        ...,
        [ 0.   , -0.005],
        [ 0.   , -0.005],
        [ 0.   , -0.005]]))

### xsec test

In [ ]:
thetas_benchmarks, xsecs_benchmarks, xsec_errors_benchmarks = sa.extract_cross_sections(
    theta=multiple_benchmark_thetas(['sm', 'morphing_basis_vector_1', 'morphing_basis_vector_2', 'morphing_basis_vector_3', 'morphing_basis_vector_4', 'morphing_basis_vector_5'])
)

thetas_morphing, xsecs_morphing, xsec_errors_morphing = sa.extract_cross_sections(
    theta=random_morphing_thetas(1000, [('gaussian', 0., 0.02), ('gaussian', 0., 0.02)])
)

In [ ]:
cmin, cmax = 0., 0.15

fig = plt.figure(figsize=(5,4))

sc = plt.scatter(thetas_morphing[:,0], thetas_morphing[:,1], c=xsecs_morphing,
            s=40., cmap='viridis', vmin=cmin, vmax=cmax,
            marker='o')

plt.scatter(thetas_benchmarks[:,0], thetas_benchmarks[:,1], c=xsecs_benchmarks,
            s=200., cmap='viridis', vmin=cmin, vmax=cmax,lw=2., edgecolor='black',
            marker='s')

cb = plt.colorbar(sc)
cb.set_label('xsec [pb]')

plt.xlim(-0.05,.05)
plt.ylim(-0.05,.05)
plt.tight_layout()
plt.show()

### Observable distributions

In [ ]:
x_bsm1, _ = sa.extract_samples_test(
    theta=constant_morphing_theta([0.02,0.]),
    n_samples=1000000,
    folder=None,
    filename=None
)

x_bsm2, _ = sa.extract_samples_test(
    theta=constant_morphing_theta([0.,0.02]),
    n_samples=1000000,
    folder=None,
    filename=None
)

In [ ]:
bins = 25
n_observables = x_sm.shape[1]
n_cols = 3
n_rows = (n_observables + n_cols - 1) // n_cols
labels = sa.observables.keys()

plt.figure(figsize=(4. * n_cols, 4. * n_rows))

for i, label in enumerate(labels):
    xmin = np.percentile(x_sm[:,i], 5.)
    xmax = np.percentile(x_sm[:,i], 95.)
    xwidth = xmax - xmin
    xmin -= xwidth * 0.1
    xmax += xwidth * 0.1
    x_range = (xmin, xmax)
    
    ax = plt.subplot(n_rows, n_cols, i+1)
       
    plt.hist(x_sm[:,i], histtype='step', range=x_range, bins=bins, lw=1.5, label=r'SM', density=True) 
    plt.hist(x_bsm1[:,i], histtype='step', range=x_range, bins=bins, lw=1.5, label=r'$f_{WWW} = 0.02$', density=True)
    plt.hist(x_bsm2[:,i], histtype='step', range=x_range, bins=bins, lw=1.5, label=r'$f_{\tilde{W}WW} = 0.02$', density=True) 
    
    if i == 0:
        plt.legend()
        
    plt.xlabel(label)
    
plt.tight_layout()
plt.savefig('observables.pdf')

## Same without cuts

In [8]:
sa_all = SampleAugmenter(sample_dir + 'samples.h5', debug=False)

08:01  Loading data from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/samples/wgamma/samples.h5
08:01  Found 2 parameters:
08:01     cWWW (LHA: dim6 1, maximal power in squared ME: (2,), range: (-0.02, 0.02))
08:01     cWWWtilde (LHA: dim6 2, maximal power in squared ME: (2,), range: (-0.02, 0.02))
08:01  Found 6 benchmarks:
08:01     sm: cWWW = 0.00e+00, cWWWtilde = 0.00e+00
08:01     morphing_basis_vector_1: cWWW = -6.07e-03, cWWWtilde = -1.84e-02
08:01     morphing_basis_vector_2: cWWW = 1.00e-02, cWWWtilde = 1.70e-02
08:01     morphing_basis_vector_3: cWWW = -1.99e-02, cWWWtilde = 1.87e-02
08:01     morphing_basis_vector_4: cWWW = 1.97e-02, cWWWtilde = -1.53e-02
08:01     morphing_basis_vector_5: cWWW = -1.65e-02, cWWWtilde = -6.33e-03
08:01  Found 27 observables: et_miss, phi_miss, e_visible, eta_visible, e_l1, pt_l1, eta_l1, phi_l1, e_a1, pt_a1, eta_a1, phi_a1, e_j1, pt_j1, eta_j1, phi_j1, deltaphi_l1_met, deltaphi_a1_met, m_l1_met, pt_l1_met, m_l1_a1, deltaeta

### SALLY training data

In [10]:
for i in range(1):
    _, _, _ = sa_all.extract_samples_train_local(
        theta=constant_morphing_theta([0.,0.]),
        n_samples=1000000,
        folder=sample_dir + 'train_local',
        filename='train_' + str(i)
    )

08:05  Extracting training sample for local score regression. Sampling and score evaluation according to ('theta', array([0., 0.]))
08:05  Effective number of samples: 31840.86847466132


### RASCAL training data

In [9]:
for i in range(1):
    _ = sa_all.extract_samples_train_ratio(
        theta0=random_morphing_thetas(1000, [('gaussian', 0., 0.005), ('gaussian', 0., 0.005)]),
        theta1=constant_morphing_theta([0.,0.]),
        n_samples=100000,
        folder=sample_dir + 'train_ratio',
        filename='train_' + str(i)
    )

08:01  Extracting training sample for ratio-based methods. Numerator hypothesis: ('random', (1000, [('gaussian', 0.0, 0.005), ('gaussian', 0.0, 0.005)])), denominator hypothesis: ('theta', array([0., 0.]))
08:03  Effective number of samples: mean 29061.326941483705, with individual thetas ranging from 21126.821551370085 to 31837.14656947281
08:05  Effective number of samples: mean 31840.86847466132, with individual thetas ranging from 31840.86847466132 to 31840.86847466132


### SCANDAL training data

In [13]:
for i in range(1):
    _, _, _ = sa_all.extract_samples_train_global(
        theta=random_morphing_thetas(10000, [('gaussian', 0., 0.005), ('gaussian', 0., 0.005)]),
        n_samples=100000,
        folder=sample_dir + 'train_scandal',
        filename='train_' + str(i)
    )

08:25  Extracting training sample for non-local score-based methods. Sampling and score evaluation according to ('random', (10000, [('gaussian', 0.0, 0.005), ('gaussian', 0.0, 0.005)]))
09:05  Effective number of samples: mean 29061.722971376337, with individual thetas ranging from 22171.365105915786 to 31818.780204395815


### Validation and test data

In [ ]:
_, _ = sa_all.extract_samples_train_plain(
    theta=constant_morphing_theta([0.,0.]),
    n_samples=1000000,
    folder=sample_dir + 'validation',
    filename='validation'
)

In [ ]:
_, _ = sa_all.extract_samples_test(
    theta=constant_morphing_theta([0.,0.]),
    n_samples=1000000,
    folder=sample_dir + 'test',
    filename='test'
)

In [12]:
sa_all.extract_samples_test(
    theta=constant_morphing_theta([0.,0.]),
    n_samples=100000,
    folder=sample_dir + 'test_sm',
    filename='test'
)

09:35  Extracting evaluation sample. Sampling according to ('theta', array([0., 0.]))
09:35  Effective number of samples: 31624.695477491


(array([[ 33.63955688,  -1.32547581,  78.75690037, ...,   4.8128867 ,
          45.5395498 ,   1.25617526],
        [ 34.86075592,  -1.12120962,  61.00724132, ...,   9.202712  ,
          32.519492  ,   0.65004966],
        [ 24.37664986,  -0.35482651,  73.75482329, ...,  17.13900984,
          25.77555574,  -0.81200949],
        ...,
        [ 32.48851776,   0.85764343,  69.83294366, ...,   7.05666343,
          37.67651509,  -0.6945806 ],
        [ 27.93987274,   1.27250886, 204.45277512, ...,  22.22741193,
          15.90669642,  -2.4953326 ],
        [ 35.40591049,   2.32230139,  77.60011941, ...,   3.1489973 ,
          38.86250583,   0.61047389]]), array([[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]))

In [9]:
sa_all.extract_samples_test(
    theta=constant_morphing_theta([0.02,0.]),
    n_samples=100000,
    folder=sample_dir + 'test_www',
    filename='test'
)

09:59  Extracting evaluation sample. Sampling according to ('theta', array([0.02, 0.  ]))
09:59  Effective number of samples: 3095.4724877464905


(array([[ 4.61141739e+01, -2.73424649e+00,  2.27482723e+02, ...,
          5.63601857e+01,  3.77629742e+01, -3.98108857e-01],
        [ 4.54617882e+01,  1.26141322e+00,  1.24027757e+02, ...,
          2.79403951e+01,  2.87716368e+01, -2.59429185e+00],
        [ 2.92661781e+01,  2.03325009e+00,  6.82095041e+01, ...,
          3.73196028e+01,  5.97169686e+00, -2.97392435e-02],
        ...,
        [ 4.00937996e+01, -1.14860785e+00,  1.92984388e+02, ...,
          7.46425158e+01,  1.69630078e-01, -2.93841221e+00],
        [ 2.48513508e+01,  1.49243534e-01,  6.84489512e+01, ...,
          3.63272853e+01,  3.05801054e+01,  2.40797754e+00],
        [ 5.07174911e+01,  8.88021588e-02,  2.71527280e+02, ...,
          1.47594181e+01,  7.22855281e+01,  1.06345882e+00]]),
 array([[0.02, 0.  ],
        [0.02, 0.  ],
        [0.02, 0.  ],
        ...,
        [0.02, 0.  ],
        [0.02, 0.  ],
        [0.02, 0.  ]]))

In [10]:
sa_all.extract_samples_test(
    theta=constant_morphing_theta([0.,0.02]),
    n_samples=100000,
    folder=sample_dir + 'test_wwwtilde',
    filename='test'
)

09:59  Extracting evaluation sample. Sampling according to ('theta', array([0.  , 0.02]))
09:59  Effective number of samples: 3098.0642083404823


(array([[ 4.41705627e+01, -8.95153940e-01,  7.50651612e+01, ...,
          2.85605103e+01,  6.37702337e+01, -1.79635355e+00],
        [ 6.55903015e+01,  1.13249612e+00,  6.60149519e+02, ...,
          1.16195792e+02,  1.72467281e+00,  1.96026153e+00],
        [ 3.18176022e+01,  4.11449909e-01,  9.08938832e+01, ...,
          1.92315213e+01,  2.97873467e+01,  2.23080913e+00],
        ...,
        [ 4.04289017e+01,  1.85120416e+00,  4.01068205e+01, ...,
          1.62859981e+00,  5.16281080e+01,  9.29954165e-01],
        [ 4.90747871e+01,  1.97064793e+00,  1.84243887e+02, ...,
          5.34057040e+01,  5.14223205e+01, -1.61017218e+00],
        [ 3.32412987e+01, -1.32163799e+00,  7.02739579e+01, ...,
          3.13776623e+01,  5.05438720e+01,  2.84102456e+00]]),
 array([[0.  , 0.02],
        [0.  , 0.02],
        [0.  , 0.02],
        ...,
        [0.  , 0.02],
        [0.  , 0.02],
        [0.  , 0.02]]))