# Evaluate Fisher information

Johann Brehmer, Kyle Cranmer, Felix Kling, Duccio Pappadopulo, Josh Ruderman 2018

In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import matplotlib
from matplotlib import pyplot as plt
% matplotlib inline
import logging
import os

import madminer.core
from madminer.fisherinformation import FisherInformation
from madminer.plotting import plot_fisher_information_contours_2d

logging.basicConfig(format='%(asctime)s  %(message)s', datefmt='%H:%M')

In [3]:
base_dir = '/Users/johannbrehmer/work/projects/madminer/diboson_mining/'
mg_dir = '/Users/johannbrehmer/work/projects/madminer/MG5_aMC_v2_6_2/'

In [4]:
sample_dir = base_dir + 'data/samples/wgamma/'
card_dir = base_dir + 'cards/wgamma/'
ufo_model_dir = card_dir + 'SMWgamma_UFO'
run_card_dir = card_dir + 'run_cards/'
mg_process_dir = base_dir + 'data/mg_processes/wgamma/'
log_dir = base_dir + 'logs/wgamma/'
temp_dir = base_dir + 'data/temp'
delphes_dir = mg_dir + 'Delphes'
model_dir = base_dir + 'data/models/wgamma/'
result_dir = base_dir + 'data/results/wgamma/'

## Settings

In [5]:
weight_settings = [None, 1., 10., 100.]
weight_setting_filenames = ['', '_w1', '_w10', '_w100']

## FisherInformation instances

In [6]:
fisher_all = FisherInformation(sample_dir + 'samples.h5', debug=True)
fisher_tight = FisherInformation(sample_dir + 'samples_tight.h5', debug=True)

11:17  
11:17  ------------------------------------------------------------
11:17  |                                                          |
11:17  |  MadMiner v2018.10.30                                    |
11:17  |                                                          |
11:17  |           Johann Brehmer, Kyle Cranmer, and Felix Kling  |
11:17  |                                                          |
11:17  ------------------------------------------------------------
11:17  
11:17  Loading data from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/samples/wgamma/samples.h5
11:17  Found 2 parameters:
11:17     cWWW (LHA: dim6 1, maximal power in squared ME: (2,), range: (-0.1, 0.1))
11:17     cWWWtilde (LHA: dim6 2, maximal power in squared ME: (2,), range: (-0.1, 0.1))
11:17  Found 6 benchmarks:
11:17     sm: cWWW = 0.00e+00, cWWWtilde = 0.00e+00
11:17     morphing_basis_vector_1: cWWW = -9.39e-02, cWWWtilde = 0.07
11:17     morphing_basis_vector_2: cWWW = 0.

## Truth-level info

In [8]:
fisher_info, cov = fisher_all.calculate_fisher_information_full_truth(
    theta=[0.,0.],
    luminosity = 300000.
)

print(fisher_info)
print(cov)

np.save(result_dir + 'information_parton.npy', fisher_info)
np.save(result_dir + 'information_covariance_parton.npy', cov)


[[65934104.21930647   129129.18318053]
 [  129129.18318053 67630934.40000063]]
[[[[ 2.04267908e+08 -1.45959868e+08]
   [-1.45959868e+08  9.48044516e+07]]

  [[-1.45959868e+08  1.12503795e+08]
   [ 1.12503795e+08 -8.09125512e+07]]]


 [[[-1.45959868e+08  1.12503795e+08]
   [ 1.12503795e+08 -8.09125512e+07]]

  [[ 9.48044516e+07 -8.09125512e+07]
   [-8.09125512e+07  6.89994123e+07]]]]


In [9]:
fisher_info, cov = fisher_tight.calculate_fisher_information_full_truth(
    theta=[0.,0.],
    luminosity = 300000.
)

print(fisher_info)
print(cov)

np.save(result_dir + 'information_parton_tight.npy', fisher_info)
np.save(result_dir + 'information_covariance_parton_tight.npy', cov)


[[33006561.30886249 -1465627.07389662]
 [-1465627.07389662 36806936.29824117]]
[[[[ 1.00528805e+08  1.32989781e+08]
   [ 1.32989781e+08  1.59547532e+08]]

  [[ 1.32989781e+08  2.84190997e+08]
   [ 2.84190997e+08 -1.29787414e+08]]]


 [[[ 1.32989781e+08  2.84190997e+08]
   [ 2.84190997e+08 -1.29787414e+08]]

  [[ 1.59547532e+08 -1.29787414e+08]
   [-1.29787414e+08  2.41959302e+09]]]]


## Rate-only info

In [7]:
fisher_info, cov = fisher_all.calculate_fisher_information_rate(
    theta=[0.,0.],
    luminosity = 300000.
)

print(fisher_info)
print(cov)

np.save(result_dir + 'information_xsec.npy', fisher_info)
np.save(result_dir + 'information_covariance_xsec.npy', cov)


[[ 2.24879374e+03 -6.41420859e+00]
 [-6.41420859e+00  1.82951736e-02]]
[[[[ 2.44952006e+05 -3.53394225e+05]
   [-3.53394225e+05  2.01397177e+03]]

  [[-3.53394225e+05  5.09844685e+05]
   [ 5.09844685e+05 -2.90557323e+03]]]


 [[[-3.53394225e+05  5.09844685e+05]
   [ 5.09844685e+05 -2.90557323e+03]]

  [[ 2.01397177e+03 -2.90557323e+03]
   [-2.90557323e+03  1.65586816e+01]]]]


In [8]:
fisher_info, cov = fisher_tight.calculate_fisher_information_rate(
    theta=[0.,0.],
    luminosity = 300000.
)

print(fisher_info)
print(cov)

np.save(result_dir + 'information_xsec_tight.npy', fisher_info)
np.save(result_dir + 'information_covariance_xsec_tight.npy', cov)



[[329.18596818 182.20807705]
 [182.20807705 100.85418746]]
[[[[  960.75023738 -1006.11365397]
   [-1006.11365397 -1408.13946438]]

  [[-1006.11365397  1053.61897954]
   [ 1053.61897954  1474.62710565]]]


 [[[-1006.11365397  1053.61897954]
   [ 1053.61897954  1474.62710565]]

  [[-1408.13946438  1474.62710565]
   [ 1474.62710565  2063.86287924]]]]


## Full Fisher info (ML)

In [ ]:
means, covs = fisher_all.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_all',
    unweighted_x_sample_file = sample_dir + 'test/x_test.npy',
    ensemble_vote_expectation_weight=weight_settings
)

print(means[0])

for weight_filename, mean, cov in zip(weight_setting_filenames, means, covs):
    np.save(result_dir + 'information_mean_full{}.npy'.format(weight_filename), mean)
    np.save(result_dir + 'information_covariance_full{}.npy'.format(weight_filename), cov)

In [ ]:
means, covs = fisher_tight.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_all_tight',
    unweighted_x_sample_file = sample_dir + 'test_tight/x_test.npy',
    ensemble_vote_expectation_weight=weight_settings
)

print(means[0])

for weight_filename, mean, cov in zip(weight_setting_filenames, means, covs):
    np.save(result_dir + 'information_mean_full_tight{}.npy'.format(weight_filename), mean)
    np.save(result_dir + 'information_covariance_full_tight{}.npy'.format(weight_filename), cov)
    

## Info in observables (ML)

In [ ]:
means, covs = fisher_tight.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_resurrection_tight',
    unweighted_x_sample_file = sample_dir + 'test_tight/x_test.npy',
    ensemble_vote_expectation_weight=weight_settings
)

print(means[0])

for weight_filename, mean, cov in zip(weight_setting_filenames, means, covs):
    np.save(result_dir + 'information_mean_resurrection_tight{}.npy'.format(weight_filename), mean)
    np.save(result_dir + 'information_covariance_resurrection_tight{}.npy'.format(weight_filename), cov)
    

## Histogram info

In [6]:
filenames = ['met', 'ptl', 'pta', 'deltaphi_lv', 'deltaphi_la', 'phi_resurrection']
observables = ['et_miss', 'pt_l1', 'pt_a1', 'deltaphi_l1_met', 'deltaphi_l1_a1', 'phi_resurrection']
bins = 25

In [7]:
for filename, obs in zip(filenames, observables):
    info, cov = fisher_tight.calculate_fisher_information_hist1d(
        theta=[0.,0.],
        luminosity=300000.,
        observable=obs,
        nbins=bins,
        histrange=None
    )
    
    print(filename)
    print(info)
    print(cov)
    
    np.save(result_dir + 'information_histo_{}_tight.npy'.format(filename), info)
    np.save(result_dir + 'information_covariance_histo_{}_tight.npy'.format(filename), cov)
    

11:05  Automatic dynamic binning: bin boundaries [  70.0026474    83.99138581   86.76307418   89.95329672   93.54304457
   97.03399445  100.7647261   104.27209382  109.33224055  114.38022429
  119.96125777  124.26446931  129.05766385  135.23042878  141.72854586
  149.10647628  156.77495164  165.52919388  175.75762136  187.32936055
  202.01050292  221.84061573  247.29611575  283.74027025  344.89002448
 3293.30224609]
/Users/johannbrehmer/work/projects/madminer/madminer/madminer/fisherinformation.py:876: RuntimeWarning: divide by zero encountered in true_divide
  inv_sigma = sanitize_array(1.0 / sigma)  # Shape (n_events,)


met
[[ 5026.11434659 -1598.13607084]
 [-1598.13607084  2570.97139915]]
[[[[ 499079.85646866  189170.74750245]
   [ 189170.74750245 -228702.9519823 ]]

  [[ 189170.74750245  102436.68275093]
   [ 102436.68275093    4834.95957741]]]


 [[[ 189170.74750245  102436.68275093]
   [ 102436.68275093    4834.95957741]]

  [[-228702.9519823     4834.95957741]
   [   4834.95957741  450884.05337728]]]]


11:06  Automatic dynamic binning: bin boundaries [   70.01407719    86.55500082    91.68231844    95.60482839
   102.30460893   107.78395903   114.36909348   120.30484038
   127.53742745   133.9118414    139.20196344   147.51164308
   156.01740185   167.32718093   176.47669834   185.38598045
   196.22807842   207.53469288   225.1394547    247.92520457
   276.97294609   309.80516652   365.73978414   455.03885944
   595.40708659 10910.87356555]


ptl
[[ 2733.80814139 -1302.1744936 ]
 [-1302.1744936   5806.37914193]]
[[[[ 380746.51993592 -328772.32863127]
   [-328772.32863127  206927.19198174]]

  [[-328772.32863127  407050.36664174]
   [ 407050.36664174 -157308.97603122]]]


 [[[-328772.32863127  407050.36664174]
   [ 407050.36664174 -157308.97603122]]

  [[ 206927.19198174 -157308.97603122]
   [-157308.97603122  244103.20805551]]]]


11:07  Automatic dynamic binning: bin boundaries [ 290.08248901  309.9334986   318.24083386  328.76538653  339.79727075
  352.41152983  363.43953839  373.24901684  388.54881176  402.51124614
  420.19677718  439.49117372  454.58263603  473.48290936  491.45754346
  507.87284141  529.29275083  557.0682178   590.65741499  631.50235191
  674.97195162  731.20534798  805.30038209  922.65290537 1130.77729687
 5671.93261719]


pta
[[4171.9640489  -709.22872092]
 [-709.22872092 5091.34205664]]
[[[[ 796309.92721633  357122.92475301]
   [ 357122.92475301  135767.10319196]]

  [[ 357122.92475301  875829.11998037]
   [ 875829.11998037 1073349.6544226 ]]]


 [[[ 357122.92475301  875829.11998037]
   [ 875829.11998037 1073349.6544226 ]]

  [[ 135767.10319196 1073349.6544226 ]
   [1073349.6544226  1897968.7894634 ]]]]


11:08  Automatic dynamic binning: bin boundaries [-1.62805717e+01 -6.54821258e-01 -4.47467246e-01 -3.66262435e-01
 -2.84017814e-01 -2.30673996e-01 -1.89236298e-01 -1.46312161e-01
 -1.13338132e-01 -8.56980246e-02 -5.84395530e-02 -3.45336585e-02
 -1.32330694e-02  9.28529690e-03  2.53340023e-02  5.13142976e-02
  7.85159593e-02  9.89369330e-02  1.31770344e-01  1.61928526e-01
  2.14148916e-01  2.70689765e-01  3.50319167e-01  4.69508461e-01
  7.35947772e-01  1.62769635e+01]


deltaphi_lv
[[83537.82754702   473.67369734]
 [  473.67369734  4925.89536767]]
[[[[ 8.38855396e+08 -6.71292699e+08]
   [-6.71292699e+08 -5.10584015e+08]]

  [[-6.71292699e+08  9.70506536e+08]
   [ 9.70506536e+08  6.58789836e+08]]]


 [[[-6.71292699e+08  9.70506536e+08]
   [ 9.70506536e+08  6.58789836e+08]]

  [[-5.10584015e+08  6.58789836e+08]
   [ 6.58789836e+08  4.80354736e+08]]]]


11:10  Automatic dynamic binning: bin boundaries [-16.08807302  -3.62551839  -3.48626152  -3.37066347  -3.279995
  -3.21677654  -3.16140671  -3.11607165  -3.06875757  -3.01115849
  -2.953066    -2.84334471  -2.63034423   2.56619804   2.76166875
   2.88677697   2.9753795    3.04968097   3.09426614   3.15441733
   3.20363396   3.2733198    3.36851322   3.45724478   3.62721455
  16.14705825]


deltaphi_la
[[32714.38732062   693.35602541]
 [  693.35602541  3099.01118511]]
[[[[ 87699336.75416616  26892576.82923355]
   [ 26892576.82923355 -18106803.8228315 ]]

  [[ 26892576.82923355  24954248.89444879]
   [ 24954248.89444879    386975.36868829]]]


 [[[ 26892576.82923355  24954248.89444879]
   [ 24954248.89444879    386975.36868829]]

  [[-18106803.8228315     386975.36868829]
   [   386975.36868829  14330883.55161038]]]]


11:11  Automatic dynamic binning: bin boundaries [-13.14157996  -3.06355927  -2.850798    -2.36411109  -1.7392082
  -1.33156132  -0.79582691  -0.33547944  -0.1229195   -0.02359715
   0.           0.           0.           0.           0.
   0.           0.05651435   0.21782831   0.54935067   1.17759982
   1.55131634   1.93577876   2.54953364   2.90038152   3.04982653
  13.14157501]


phi_resurrection
[[5784.38513982  376.60484451]
 [ 376.60484451 6919.76703796]]
[[[[ 1.22925210e+08 -6.51142669e+07]
   [-6.51142669e+07 -1.72543563e+07]]

  [[-6.51142669e+07  1.82762609e+08]
   [ 1.82762609e+08 -3.00205683e+07]]]


 [[[-6.51142669e+07  1.82762609e+08]
   [ 1.82762609e+08 -3.00205683e+07]]

  [[-1.72543563e+07 -3.00205683e+07]
   [-3.00205683e+07  6.77544927e+08]]]]
