# Evaluate Fisher information

Johann Brehmer, Kyle Cranmer, Marco Farina, Felix Kling, Duccio Pappadopulo, Josh Ruderman 2018

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline
import logging
import os

import madminer.core
from madminer.fisherinformation import FisherInformation
from madminer.plotting import plot_fisher_information_contours_2d

logging.basicConfig(format='%(asctime)-5.5s %(name)-20.20s %(levelname)-7.7s %(message)s', datefmt='%H:%M', level=logging.DEBUG)


04:58 matplotlib.pyplot    DEBUG   Loaded backend module://ipykernel.pylab.backend_inline version unknown.


In [2]:
base_dir = '/Users/johannbrehmer/work/projects/madminer/diboson_mining/'
mg_dir = '/Users/johannbrehmer/work/projects/madminer/MG5_aMC_v2_6_4/'

In [3]:
sample_dir = base_dir + 'data/samples/wgamma/'
card_dir = base_dir + 'cards/wgamma/'
ufo_model_dir = card_dir + 'SMWgamma_UFO'
run_card_dir = card_dir + 'run_cards/'
mg_process_dir = base_dir + 'data/mg_processes/wgamma/'
log_dir = base_dir + 'logs/wgamma/'
temp_dir = base_dir + 'data/temp'
delphes_dir = mg_dir + 'Delphes'
model_dir = base_dir + 'data/models/wgamma/'
result_dir = base_dir + 'data/results/wgamma/'

## FisherInformation instances

In [4]:
fisher_all = FisherInformation(sample_dir + 'samples.h5')
fisher_tight = FisherInformation(sample_dir + 'samples_tight.h5')

04:58 madminer.fisherinfor INFO    Loading data from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/samples/wgamma/samples.h5
04:58 madminer.utils.inter INFO    HDF5 file does not contain is_reference field.
04:58 madminer.fisherinfor INFO    Found 2 parameters:
04:58 madminer.fisherinfor INFO       cWWW (LHA: dim6 1, maximal power in squared ME: (2,), range: (-0.02, 0.02))
04:58 madminer.fisherinfor INFO       cWWWtilde (LHA: dim6 2, maximal power in squared ME: (2,), range: (-0.02, 0.02))
04:58 madminer.fisherinfor INFO    Found 6 benchmarks, of which 6 physical:
04:58 madminer.fisherinfor INFO       sm: cWWW = 0.00e+00, cWWWtilde = 0.00e+00
04:58 madminer.fisherinfor INFO       morphing_basis_vector_1: cWWW = -6.07e-03, cWWWtilde = -1.84e-02
04:58 madminer.fisherinfor INFO       morphing_basis_vector_2: cWWW = 1.00e-02, cWWWtilde = 1.70e-02
04:58 madminer.fisherinfor INFO       morphing_basis_vector_3: cWWW = -1.99e-02, cWWWtilde = 1.87e-02
04:58 madminer.fisherinfo

## Truth-level info

In [5]:
fisher_info, cov = fisher_all.calculate_fisher_information_full_truth(
    theta=[0.,0.],
    luminosity = 300000.
)

np.save(result_dir + 'information_parton.npy', fisher_info)
np.save(result_dir + 'information_covariance_parton.npy', cov)


In [6]:
fisher_info, cov = fisher_tight.calculate_fisher_information_full_truth(
    theta=[0.,0.],
    luminosity = 300000.
)

np.save(result_dir + 'information_parton_tight.npy', fisher_info)
np.save(result_dir + 'information_covariance_parton_tight.npy', cov)


## Rate-only info

In [7]:
fisher_info, cov = fisher_all.calculate_fisher_information_rate(
    theta=[0.,0.],
    luminosity = 300000.
)

np.save(result_dir + 'information_xsec.npy', fisher_info)
np.save(result_dir + 'information_covariance_xsec.npy', cov)


In [8]:
fisher_info, cov = fisher_tight.calculate_fisher_information_rate(
    theta=[0.,0.],
    luminosity = 300000.
)

np.save(result_dir + 'information_xsec_tight.npy', fisher_info)
np.save(result_dir + 'information_covariance_xsec_tight.npy', cov)


## Full Fisher info (ML)

In [9]:
mean, cov = fisher_all.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_all',
    mode="score"
)

np.save(result_dir + 'information_full.npy', mean)
np.save(result_dir + 'information_covariance_full.npy', cov)

05:06 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all/ensemble.json
05:06 madminer.ml          INFO    Found ensemble with 5 estimators and expectations [[-0.02700534  0.04536112]
 [-0.03448038  0.00768808]
 [-0.01489388 -0.00805724]
 [ 0.02017411  0.01007602]
 [ 0.06479936 -0.00081921]]
05:06 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all/estimator_0_settings.json
05:06 madminer.ml          DEBUG     Found method sally, 33 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features None
05:06 madminer.ml          DEBUG     Found input scaling information: means [ 4.79277618e+01 -3.40800826e-01  3.11957718e+02  9.10092281e-01
  1.22878796e+02  5.67917248e+01  6.91620288e-01  5.98299385e-01
  1.53849347e+02  6.93091146e+01 -2.36313900e-02 -2.58923597e-01
 

05:06 madminer.fisherinfor DEBUG   Found 2 parameters in SALLY model, matching 2 physical parameters in MadMiner file
05:06 madminer.fisherinfor DEBUG   Not including nuisance parameters
05:08 madminer.fisherinfor DEBUG   Total cross section: 0.02290457732754176 pb
05:08 madminer.fisherinfor INFO    Evaluating rate Fisher information
05:08 madminer.utils.inter WARNING include_nuisance_parameters=False without benchmark_is_nuisance information. Returning all weights.
05:11 madminer.utils.inter WARNING include_nuisance_parameters=False without benchmark_is_nuisance information. Returning all weights.
05:11 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 1 / 5
05:11 madminer.ml          DEBUG   Evaluating Fisher information for 5 estimators in ensemble
05:11 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1., 1., 1.])]
05:11 madminer.ml          DEBUG   Evaluating estimators for x = [ 3.48704803e+02  9.60082784e-02  6.39579985e+02 

05:11 madminer.ml          DEBUG   Starting evaluation for estimator 1 / 5 in ensemble
05:11 madminer.ml          DEBUG   Loading evaluation data
05:11 madminer.ml          DEBUG   Starting score evaluation
05:11 madminer.ml          DEBUG   Estimator 0 predicts t(x) = [-46.52287     4.3306413]
05:11 madminer.ml          DEBUG   Starting evaluation for estimator 2 / 5 in ensemble
05:11 madminer.ml          DEBUG   Loading evaluation data
05:11 madminer.ml          DEBUG   Starting score evaluation
05:11 madminer.ml          DEBUG   Estimator 1 predicts t(x) = [-77.86564   14.445775]
05:11 madminer.ml          DEBUG   Starting evaluation for estimator 3 / 5 in ensemble
05:11 madminer.ml          DEBUG   Loading evaluation data
05:11 madminer.ml          DEBUG   Starting score evaluation
05:11 madminer.ml          DEBUG   Estimator 2 predicts t(x) = [-35.793056   6.251011]
05:11 madminer.ml          DEBUG   Starting evaluation for estimator 4 / 5 in ensemble
05:11 madminer.ml          DE

05:12 madminer.ml          DEBUG   Starting evaluation for estimator 5 / 5 in ensemble
05:12 madminer.ml          DEBUG   Loading evaluation data
05:12 madminer.ml          DEBUG   Starting score evaluation
05:12 madminer.ml          DEBUG   Estimator 4 predicts t(x) = [93.99871    2.2495794]
05:12 madminer.ml          DEBUG   Now x = [ 4.42403870e+02 -1.34472990e+00  1.14852080e+03 -6.69094475e-01
  5.61544129e+02  4.58026520e+02 -6.60262346e-01 -1.43163490e+00
  1.16879089e+03  8.46727417e+02 -8.46678317e-01  1.79589343e+00
  2.54325429e+01  2.40908375e+01  2.38282263e-01  1.28139317e+00
  1.30000000e+01  1.24977942e+03  3.05159973e+02  1.33541975e+03
  3.92365493e+02  8.99580719e+02  4.04323983e+02 -3.22752833e+00
 -8.69050026e-02  3.14062333e+00  1.86415970e-01  1.85429691e+03
  6.49402587e+01  3.91077538e+01 -2.60200394e+00 -4.75614882e-01
 -4.75614882e-01]
05:12 madminer.ml          DEBUG   Individual score predictions for first event:
 [[ 72.73061    -6.316196 ]
 [ 87.29692    -

In [10]:
mean, cov = fisher_tight.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_all_tight',
    mode="score"
)

np.save(result_dir + 'information_full_tight.npy', mean)
np.save(result_dir + 'information_covariance_full_tight.npy', cov)
    

05:12 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all_tight/ensemble.json
05:12 madminer.ml          INFO    Found ensemble with 3 estimators and expectations [[ 0.07866079 -0.32558089]
 [ 0.01908596  0.21767101]
 [-0.02144005 -0.69183141]]
05:12 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all_tight/estimator_0_settings.json
05:12 madminer.ml          DEBUG     Found method sally, 33 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features None
05:12 madminer.ml          DEBUG     Found input scaling information: means [ 1.96900372e+02  2.73389814e-03  1.11502247e+03 -1.27638474e-03
  4.57294828e+02  2.79849737e+02  1.32475006e-03 -3.04760172e-03
  9.45595736e+02  4.70017264e+02 -1.99928986e-03  6.48891487e-04
  1.34318769e+02  4.53960111e+01 -2.7796224

05:15 madminer.ml          DEBUG   Mean:
[-408.76672    25.800543]
05:15 madminer.ml          DEBUG   Covariance:
[[ 74017.875  -10469.084 ]
 [-10469.084    1482.5023]]
05:15 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([ 0.12573515, -0.33336588])]
with covariance matrix
[array([[254.63690253,  -5.51062946],
       [ -5.51062946, 131.67941289]])]
05:15 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 2 / 4
05:15 madminer.ml          DEBUG   Evaluating Fisher information for 3 estimators in ensemble
05:15 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1.])]
05:15 madminer.ml          DEBUG   Evaluating estimators for x = [ 1.86849060e+02  4.16664869e-01  4.01703742e+03  1.20790669e+00
  1.09441358e+03  3.74122070e+02  1.73595381e+00  2.26999193e-01
  1.29116736e+03  5.73426392e+02 -1.45140302e+00 -3.07080293e+00
  3.86111369e+02  9.19513702e+01 -2.11197400e+00 -5.54793954e-01
 -1.1000000

05:15 madminer.ml          DEBUG   Individual score predictions for first event:
 [[ 74.7567      3.0057514]
 [201.94302    29.66572  ]
 [115.961296   -7.6959643]]
05:15 madminer.ml          DEBUG   Mean:
[130.88701    8.325169]
05:15 madminer.ml          DEBUG   Covariance:
[[4211.173   1027.041  ]
 [1027.041    370.19604]]
05:15 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([ 0.29511717, -0.32625968])]
with covariance matrix
[array([[259.89157085,  -5.57738489],
       [ -5.57738489, 123.93917734]])]


In [11]:
mean, cov = fisher_tight.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_all',
    mode="information"
)

np.save(result_dir + 'information_full_infomode.npy', mean)
np.save(result_dir + 'information_covariance_full_infomode.npy', cov)
    

05:15 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all/ensemble.json
05:15 madminer.ml          INFO    Found ensemble with 5 estimators and expectations [[-0.02700534  0.04536112]
 [-0.03448038  0.00768808]
 [-0.01489388 -0.00805724]
 [ 0.02017411  0.01007602]
 [ 0.06479936 -0.00081921]]
05:15 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all/estimator_0_settings.json
05:15 madminer.ml          DEBUG     Found method sally, 33 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features None
05:15 madminer.ml          DEBUG     Found input scaling information: means [ 4.79277618e+01 -3.40800826e-01  3.11957718e+02  9.10092281e-01
  1.22878796e+02  5.67917248e+01  6.91620288e-01  5.98299385e-01
  1.53849347e+02  6.93091146e+01 -2.36313900e-02 -2.58923597e-01
 

05:15 madminer.fisherinfor DEBUG   Found 2 parameters in SALLY model, matching 2 physical parameters in MadMiner file
05:15 madminer.fisherinfor DEBUG   Not including nuisance parameters
05:16 madminer.fisherinfor DEBUG   Total cross section: 0.0007642437474402438 pb
05:16 madminer.fisherinfor INFO    Evaluating rate Fisher information
05:16 madminer.utils.inter WARNING include_nuisance_parameters=False without benchmark_is_nuisance information. Returning all weights.
05:17 madminer.utils.inter WARNING include_nuisance_parameters=False without benchmark_is_nuisance information. Returning all weights.
05:17 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 1 / 4
05:17 madminer.ml          DEBUG   Evaluating Fisher information for 5 estimators in ensemble
05:17 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1., 1., 1.])]
05:17 madminer.ml          DEBUG   Starting evaluation for estimator 1 / 5 in ensemble
05:17 madminer.ml        

In [12]:
mean, cov = fisher_all.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_all_shuffled',
    mode="score"
)

np.save(result_dir + 'information_full_shuffled.npy', mean)
np.save(result_dir + 'information_covariance_full_shuffled.npy', cov)

05:18 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all_shuffled/ensemble.json
05:18 madminer.ml          INFO    Found ensemble with 5 estimators and expectations [[ 0.01521948  0.03405889]
 [ 0.0681127   0.02697503]
 [-0.00113952 -0.05802982]
 [-0.02525729  0.02159016]
 [ 0.04841258 -0.03276466]]
05:18 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_all_shuffled/estimator_0_settings.json
05:18 madminer.ml          DEBUG     Found method sally, 33 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features None
05:18 madminer.ml          DEBUG     Found input scaling information: means [ 4.79277618e+01 -3.40800826e-01  3.11957718e+02  9.10092281e-01
  1.22878796e+02  5.67917248e+01  6.91620288e-01  5.98299385e-01
  1.53849347e+02  6.93091146e+01 -2.36313900e-02

05:18 madminer.fisherinfor DEBUG   Found 2 parameters in SALLY model, matching 2 physical parameters in MadMiner file
05:18 madminer.fisherinfor DEBUG   Not including nuisance parameters
05:19 madminer.fisherinfor DEBUG   Total cross section: 0.02290457732754176 pb
05:19 madminer.fisherinfor INFO    Evaluating rate Fisher information
05:19 madminer.utils.inter WARNING include_nuisance_parameters=False without benchmark_is_nuisance information. Returning all weights.
05:20 madminer.utils.inter WARNING include_nuisance_parameters=False without benchmark_is_nuisance information. Returning all weights.
05:20 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 1 / 5
05:20 madminer.ml          DEBUG   Evaluating Fisher information for 5 estimators in ensemble
05:20 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1., 1., 1.])]
05:20 madminer.ml          DEBUG   Evaluating estimators for x = [ 3.48704803e+02  9.60082784e-02  6.39579985e+02 

05:20 madminer.ml          DEBUG   Starting evaluation for estimator 1 / 5 in ensemble
05:20 madminer.ml          DEBUG   Loading evaluation data
05:20 madminer.ml          DEBUG   Starting score evaluation
05:20 madminer.ml          DEBUG   Estimator 0 predicts t(x) = [0.6032613  0.56255054]
05:20 madminer.ml          DEBUG   Starting evaluation for estimator 2 / 5 in ensemble
05:20 madminer.ml          DEBUG   Loading evaluation data
05:20 madminer.ml          DEBUG   Starting score evaluation
05:20 madminer.ml          DEBUG   Estimator 1 predicts t(x) = [0.9757041  0.33813298]
05:20 madminer.ml          DEBUG   Starting evaluation for estimator 3 / 5 in ensemble
05:20 madminer.ml          DEBUG   Loading evaluation data
05:20 madminer.ml          DEBUG   Starting score evaluation
05:20 madminer.ml          DEBUG   Estimator 2 predicts t(x) = [-0.6061179  0.2733101]
05:20 madminer.ml          DEBUG   Starting evaluation for estimator 4 / 5 in ensemble
05:20 madminer.ml          DEBU

05:20 madminer.ml          DEBUG   Starting evaluation for estimator 5 / 5 in ensemble
05:20 madminer.ml          DEBUG   Loading evaluation data
05:20 madminer.ml          DEBUG   Starting score evaluation
05:20 madminer.ml          DEBUG   Estimator 4 predicts t(x) = [-0.22754069  0.45792216]
05:20 madminer.ml          DEBUG   Now x = [ 4.42403870e+02 -1.34472990e+00  1.14852080e+03 -6.69094475e-01
  5.61544129e+02  4.58026520e+02 -6.60262346e-01 -1.43163490e+00
  1.16879089e+03  8.46727417e+02 -8.46678317e-01  1.79589343e+00
  2.54325429e+01  2.40908375e+01  2.38282263e-01  1.28139317e+00
  1.30000000e+01  1.24977942e+03  3.05159973e+02  1.33541975e+03
  3.92365493e+02  8.99580719e+02  4.04323983e+02 -3.22752833e+00
 -8.69050026e-02  3.14062333e+00  1.86415970e-01  1.85429691e+03
  6.49402587e+01  3.91077538e+01 -2.60200394e+00 -4.75614882e-01
 -4.75614882e-01]
05:20 madminer.ml          DEBUG   Individual score predictions for first event:
 [[ 0.99853253  1.1653361 ]
 [-0.43894178 

## Minimal observable set (ML)

In [13]:
mean, cov = fisher_all.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_minimal',
    mode="score"
)

np.save(result_dir + 'information_minimal.npy', mean)
np.save(result_dir + 'information_covariance_minimal.npy', cov)

05:20 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_minimal/ensemble.json
05:20 madminer.ml          INFO    Found ensemble with 3 estimators and expectations [[ 0.03727786 -0.01299251]
 [ 0.03324794 -0.02153054]
 [ 0.01043152 -0.05017371]]
05:20 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_minimal/estimator_0_settings.json
05:20 madminer.ml          DEBUG     Found method sally, 27 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
05:20 madminer.ml          DEBUG     Found input scaling information: means [ 4.79277618e+01 -3.40800826e-01  3.11957718e+02  9.10092281e-01
  1.22878796e+02  5.67917248e+01  6.91620288e-01  5.98299385e-01
  1.53849347e+02

05:23 madminer.ml          DEBUG   Individual score predictions for first event:
 [[-16.994425    6.9633718]
 [-32.38327    -4.675959 ]
 [-12.458499   -1.6414984]]
05:23 madminer.ml          DEBUG   Mean:
[-20.612064     0.21530473]
05:23 madminer.ml          DEBUG   Covariance:
[[109.06462   33.424294]
 [ 33.424294  36.454292]]
05:23 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([ 6.22984983, -0.40483237])]
with covariance matrix
[array([[151.31538034,  11.00198333],
       [ 11.00198333,   7.05966296]])]
05:23 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 2 / 5
05:23 madminer.ml          DEBUG   Evaluating Fisher information for 3 estimators in ensemble
05:23 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1.])]
05:23 madminer.ml          DEBUG   Evaluating estimators for x = [ 2.74213062e+03  1.21896529e+00  1.13832657e+03 -4.76614594e-01
  5.69163287e+02  5.10118500e+02 -4.76614594

05:23 madminer.ml          DEBUG   Individual score predictions for first event:
 [[245.38835  -18.444311]
 [ 63.19624    8.830863]
 [-77.62883   18.523668]]
05:23 madminer.ml          DEBUG   Mean:
[76.98525    2.9700735]
05:23 madminer.ml          DEBUG   Covariance:
[[26227.627  -3045.934 ]
 [-3045.934    367.4195]]
05:23 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([-2.93668414, -0.39408515])]
with covariance matrix
[array([[66.01547617,  6.53438766],
       [ 6.53438766,  7.85390728]])]
05:23 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 5 / 5
05:23 madminer.ml          DEBUG   Evaluating Fisher information for 3 estimators in ensemble
05:23 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1.])]
05:23 madminer.ml          DEBUG   Evaluating estimators for x = [ 4.42403870e+02 -1.34472990e+00  1.14852080e+03 -6.69094475e-01
  5.61544129e+02  4.58026520e+02 -6.60262346e-01 -1.431634

In [14]:
mean, cov = fisher_tight.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_minimal_tight',
    mode="score"
)

np.save(result_dir + 'information_minimal_tight.npy', mean)
np.save(result_dir + 'information_covariance_minimal_tight.npy', cov)

05:23 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_minimal_tight/ensemble.json
05:23 madminer.ml          INFO    Found ensemble with 3 estimators and expectations [[ 0.53833276 -0.0199135 ]
 [-0.22980122  0.07156279]
 [-0.1674214  -0.2771793 ]]
05:23 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_minimal_tight/estimator_0_settings.json
05:23 madminer.ml          DEBUG     Found method sally, 27 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
05:23 madminer.ml          DEBUG     Found input scaling information: means [ 1.96900372e+02  2.73389814e-03  1.11502247e+03 -1.27638474e-03
  4.57294828e+02  2.79849737e+02  1.32475006e-03 -3.04760172e-03
  9.

05:25 madminer.ml          DEBUG   Individual score predictions for first event:
 [[-107.47043    14.376001]
 [-119.28463     2.214718]
 [-514.23035   -18.562664]]
05:25 madminer.ml          DEBUG   Mean:
[-246.99513      -0.65731496]
05:25 madminer.ml          DEBUG   Covariance:
[[53595.89     3624.624  ]
 [ 3624.624     277.42538]]
05:25 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([ 0.06329122, -0.08485834])]
with covariance matrix
[array([[174.84137463,  -5.42080025],
       [ -5.42080025,  83.28775821]])]
05:25 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 2 / 4
05:25 madminer.ml          DEBUG   Evaluating Fisher information for 3 estimators in ensemble
05:25 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1.])]
05:25 madminer.ml          DEBUG   Evaluating estimators for x = [ 1.86849060e+02  4.16664869e-01  4.01703742e+03  1.20790669e+00
  1.09441358e+03  3.74122070e+02  1.73

05:25 madminer.ml          DEBUG   Individual score predictions for first event:
 [[42.671444    0.38968903]
 [76.58381     3.4141028 ]
 [55.687458    1.2847872 ]]
05:25 madminer.ml          DEBUG   Mean:
[58.314236   1.6961931]
05:25 madminer.ml          DEBUG   Covariance:
[[292.6871     26.45176  ]
 [ 26.45176     2.4137106]]
05:25 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([ 0.17983514, -0.01146542])]
with covariance matrix
[array([[173.35315466,  -4.72867784],
       [ -4.72867784,  80.26482244]])]


## Info in observables (ML)

In [15]:
mean, cov = fisher_tight.calculate_fisher_information_full_detector(
    theta=[0.,0.],
    luminosity=300000.,
    model_file=model_dir + 'sally_ensemble_phi_tight',
    mode="score"
)

np.save(result_dir + 'information_phi_tight.npy', mean)
np.save(result_dir + 'information_covariance_phi_tight.npy', cov)


05:25 madminer.ml          DEBUG   Loading ensemble setup from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_phi_tight/ensemble.json
05:25 madminer.ml          INFO    Found ensemble with 3 estimators and expectations [[ 0.29765818  0.22258498]
 [-0.24244618  0.28048807]
 [-0.2418339  -0.18093704]]
05:25 madminer.ml          DEBUG   Loading settings from /Users/johannbrehmer/work/projects/madminer/diboson_mining/data/models/wgamma/sally_ensemble_phi_tight/estimator_0_settings.json
05:25 madminer.ml          DEBUG     Found method sally, 1 observables, 2 parameters, (100, 100) hidden layers, tanh activation function, features [32]
05:25 madminer.ml          DEBUG     Found input scaling information: means [ 1.96900372e+02  2.73389814e-03  1.11502247e+03 -1.27638474e-03
  4.57294828e+02  2.79849737e+02  1.32475006e-03 -3.04760172e-03
  9.45595736e+02  4.70017264e+02 -1.99928986e-03  6.48891487e-04
  1.34318769e+02  4.53960111e+01 -2.77962243

05:27 madminer.ml          DEBUG   Mean:
[-29.927002   -3.6400635]
05:27 madminer.ml          DEBUG   Covariance:
[[0.80803895 0.24001029]
 [0.24001029 0.11375041]]
05:27 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([0.21439308, 0.11209712])]
with covariance matrix
[array([[1.10243203, 0.01356359],
       [0.01356359, 0.32246004]])]
05:27 madminer.fisherinfor INFO    Evaluating kinematic Fisher information on batch 2 / 4
05:27 madminer.ml          DEBUG   Evaluating Fisher information for 3 estimators in ensemble
05:27 madminer.ml          DEBUG     Estimator estimator_weights: [array([1., 1., 1.])]
05:27 madminer.ml          DEBUG   Evaluating estimators for x = [ 1.86849060e+02  4.16664869e-01  4.01703742e+03  1.20790669e+00
  1.09441358e+03  3.74122070e+02  1.73595381e+00  2.26999193e-01
  1.29116736e+03  5.73426392e+02 -1.45140302e+00 -3.07080293e+00
  3.86111369e+02  9.19513702e+01 -2.11197400e+00 -5.54793954e-01
 -1.10000000e+01  2.37267

05:27 madminer.ml          DEBUG   Individual score predictions for first event:
 [[ 6.2007080e+01  2.6766632e-02]
 [ 6.0887531e+01  3.3839935e-01]
 [ 6.0816990e+01 -8.0556676e-02]]
05:27 madminer.ml          DEBUG   Mean:
[61.237198    0.09486977]
05:27 madminer.ml          DEBUG   Covariance:
[[ 0.44578004 -0.03193498]
 [-0.03193498  0.04735957]]
05:27 madminer.ml          INFO    Expected per-event score (should be close to zero):
[array([0.2718847 , 0.11132503])]
with covariance matrix
[array([[1.09270899, 0.01597934],
       [0.01597934, 0.32313254]])]


## Histogram info

In [16]:
filenames = ['phi', 'met', 'ptl', 'pta', 'deltaphi_lv', 'deltaphi_la']
observables = ['phi', 'et_miss', 'pt_l1', 'pt_a1', 'deltaphi_lmet', 'deltaphi_la']
bins = 25

In [17]:
for filename, obs in zip(filenames, observables):
    print(filename)
    info, cov = fisher_tight.calculate_fisher_information_hist1d(
        theta=[0.,0.],
        luminosity=300000.,
        observable=obs,
        nbins=bins,
        histrange=None
    )
    
    np.save(result_dir + 'information_histo_{}_tight.npy'.format(filename), info)
    np.save(result_dir + 'information_covariance_histo_{}_tight.npy'.format(filename), cov)
    

phi


05:27 madminer.fisherinfor DEBUG   Automatic dynamic binning: bin boundaries [-2.91418724 -2.69553291 -2.4499801  -2.21478324 -1.96160261 -1.62465903
 -1.47272991 -1.16001152 -0.87486263 -0.623786   -0.35508208 -0.10011146
  0.15752232  0.40760321  0.66282529  0.90822179  1.16942036  1.48834885
  1.63974315  1.96574893  2.22548694  2.46516511  2.6917621   2.92639525]


met


05:29 madminer.fisherinfor DEBUG   Automatic dynamic binning: bin boundaries [ 85.33444522  91.09620147  97.15018534 103.50056922 110.12013755
 116.83991089 124.56821799 132.02441694 140.13264058 147.53900297
 156.0128475  165.0261951  174.57266192 185.00812212 196.45498662
 208.14190846 221.70090806 235.13868631 251.00961223 268.81810707
 288.83747507 314.50681218 350.91957038 417.90081389]


ptl


05:31 madminer.fisherinfor DEBUG   Automatic dynamic binning: bin boundaries [103.41843901 123.25462748 142.06454639 159.15111325 174.35635686
 188.78073347 200.5282376  213.19595906 225.05434806 236.22600767
 247.03205257 257.83975304 268.02947736 277.98897607 288.77404086
 299.84458292 311.48190975 324.94803815 340.72157691 360.40453707
 384.07680588 415.72247401 460.80293628 543.54778214]


pta


05:33 madminer.fisherinfor DEBUG   Automatic dynamic binning: bin boundaries [328.49457892 349.47528832 361.22255256 368.81640155 375.28941618
 381.97225436 388.2015205  394.84897618 402.40422202 410.42005187
 418.54010156 427.72751994 436.85216388 447.03232496 458.01431654
 470.76911984 484.54884417 500.87628481 519.8976523  541.40264638
 569.09164327 606.23769022 661.09289633 760.4414951 ]


deltaphi_lv


05:34 madminer.fisherinfor DEBUG   Automatic dynamic binning: bin boundaries [-0.5893007  -0.44079526 -0.38602731 -0.34626374 -0.31158802 -0.27620883
 -0.23906189 -0.1997264  -0.15941086 -0.11728809 -0.07478944 -0.02650361
  0.01802391  0.06353121  0.10800193  0.15057889  0.1903107   0.22973654
  0.26557292  0.30384559  0.33950108  0.38327148  0.43972988  0.57415348]


deltaphi_la


05:38 madminer.fisherinfor DEBUG   Automatic dynamic binning: bin boundaries [-3.40930577 -3.31899239 -3.26582369 -3.22568283 -3.19102166 -3.15454719
 -3.11905568 -3.08535549 -3.05019333 -3.01041514 -2.94950531 -2.80241185
  2.84374396  2.96393915  3.0153815   3.05329833  3.08770376  3.12130522
  3.15472249  3.18640076  3.22135465  3.26076154  3.31364752  3.41029273]
